config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root "main#index"
  
  get '/tasks', to: 'tasks#list', as: 'custom_tasks_list'
  resources :categories do
    resources :tasks
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
    belongs_to :user
    has_many :tasks, dependent: :destroy

    validates :title, presence: true, length: { maximum: 20 }
    validates :title, uniqueness: { scope: :user_id }
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :category

  validates :name, presence: true, length: { maximum: 100 }
  validates :notes, length: { maximum: 2000 }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

         has_many :categories
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    # force user to redirect to login page if logged out
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
    before_action :authenticate_user!
    before_action :correct_user, only: [:show, :edit, :update, :destory]

    def index
        # @categories = Category.all
        @categories = current_user.categories
    end

    def show
        redirect_to category_tasks_path(@category)
    end
    def new
        @category = current_user.categories.build
    end
    
    def create
        @category = current_user.categories.build(category_params)
    
        if @category.save
            redirect_to categories_path, notice: "Successfully created a category!"
        else
            render :new
        end
    end

    def edit
    end

    def update
        if @category.update(category_params)
            redirect_to categories_path, notice: "Successfully edited a category!"
        else
            render :edit
        end
    end

    def destroy
        correct_user # ? not sure why, but destroy doesn't work if I don't explicitly call correct_user here (even if I have a before_action)
        @category.destroy
    
        redirect_to categories_path, notice: "Successfully deleted a category!"
    end

    def correct_user
        @category = current_user.categories.find_by(id: params[:id])
        redirect_to categories_path, notice: "Not authorized to access/edit this." if @category.nil?
    end

    private        
        def category_params
            params.require(:category).permit(:title, :user_id)
        end
end

app/controllers/main_controller.rb
class MainController < ApplicationController
    def index
        if user_signed_in?
            redirect_to categories_path
        else
            redirect_to new_user_session_path
        end
    end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
    before_action :authenticate_user!
    before_action :set_category, except: [:list]
    before_action :set_task, only: [:show, :edit, :update, :destroy]

    def index        
        # get all tasks in categories belonging to current_user
        @tasks = @category.tasks

        # get specific lists of tasks
        @tasks_today = @tasks.where("date >= ? and date < ?", Date.current, Date.current+1).order("date, category_id")
        @tasks_overdue = @tasks.where("date < ?", Date.current).order("date, category_id")
        @tasks_no_date = @tasks.where(date: nil).order("category_id")
        @tasks_after_today = @tasks.where("date > ?", Date.current).order("date")
    end

    def show
    end
    
    def new
        @task = @category.tasks.new
    end
    
    def create
        @task = @category.tasks.new(task_params)
        if @task.save
            redirect_to category_tasks_path(@category), notice: "Successfully created a task!"
        else
            render :new
        end
    end

    def edit
    end

    def update
        if @task.update(task_params)
            # redirect_to @task
            redirect_to category_tasks_path(@category), notice: "Successfully updated task!"
        else
            render :edit
        end
    end

    def destroy
        @task.destroy
        redirect_to category_path(@category), notice: "Successfully deleted task!"
    end

    # GET /tasks
    def list
        # get categories the user owns
        @categories = current_user.categories
        redirect_to categories_path, notice: "Not authorized to access/edit this." if @categories.nil?
        
        # get all tasks in categories belonging to current_user
        @tasks = Task.where(category_id: [@categories.select(:id)])#.order("date DESC, category_id")

        # get specific lists of tasks
        @tasks_today = @tasks.where("date >= ? and date < ?", Date.current, Date.current+1).order("date, category_id")
        @tasks_overdue = @tasks.where("date < ?", Date.current).order("date, category_id")
        @tasks_no_date = @tasks.where(date: nil).order("category_id")
        @tasks_after_today = @tasks.where("date > ?", Date.current).order("date")
    end
    
    private
        def set_category
            @category = current_user.categories.find_by(id: params[:category_id])
            redirect_to categories_path, notice: "Not authorized to access/edit this." if @category.nil?
        end

        def set_task
            @task = @category.tasks.find(params[:id])
        end

        def task_params
            params.require(:task).permit(:name, :notes, :date, :complete)
        end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/categories/_card.html.erb
<div class="w-80 xl:w-1/4">
    <div class="
    flex flex-col justify-between
    rounded-lg shadow-md hover:shadow-xl
    px-7 py-6 h-56 m-3
    bg-gray-700
    transition duration-200
    ">
        <h1 class="text-3xl truncate">
            <a href=<%= category_path(category) %>>
                <span class = "has-tooltip">
                    <%= category.title %>
                    <%= render 'shared/tooltip', msg: category.title %>
                </span>
            </a>
        </h1>
        
        <%# details %>
        <div class="text-sm">
            <p class="text-gray-300">
                <i class="fas fa-thumbtack text-sm mr-2"></i><%= category.tasks.length%> Tasks
            </p>
            <%# change to Updated X days/months ago %>
            <p class="text-gray-400">
                <i class="fas fa-sync text-sm mr-2"></i>Last Updated: <%= category.updated_at.strftime("%B %d, %Y") %>
            </p>
        </div>

        <%# options %>
        <div class="
        flex flex-row justify-center items-stretch
        text-center text-white text-xl
        bg-gray-600
        mt-6
        rounded-lg
        ">        
            <%= link_to category, class: "
            w-full px-4
            text-green-400 hover:text-white
            hover:bg-green-800
            cursor-pointer
            rounded-l-lg
            select-none
            transition duration-200
            " do %>
                <i class="fas fa-expand-arrows-alt"></i> 
                <%# Expand %>
            <% end  %>

            <%= link_to edit_category_path(category), class: "
            w-full px-4
            text-blue-400 hover:text-white
            hover:bg-blue-800
            cursor-pointer
            select-none
            transition duration-200
            " do %>
                <i class="far fa-edit"></i> 
                <%# Edit %>
            <% end  %>

            <%= link_to category, method: :delete, data: { confirm: 'Are you sure you want to delete this category?' }, class: "
            w-full px-4
            text-red-400 hover:text-white
            hover:bg-red-800
            cursor-pointer
            rounded-r-lg
            select-none
            transition duration-200
            " do %>
                <i class="far fa-trash-alt"></i> 
                <%# Delete %>
            <% end  %>
        </div>
    </div>
</div>

app/views/categories/_form.html.erb
<%= form_with model: @category do |form| %>
    <div class="flex flex-col mb-8">
        <%= form.label :title, class: "text-xl font-semibold" %>
        <%= form.text_field :title, class: "
        w-full px-4 py-2
        text-base text-black
        border border-gray-300 rounded-md
        focus:outline-none focus:border-gray-500
        " %>
        <% @category.errors.full_messages_for(:title).each do |message| %>
            <div><%= message %></div>
        <% end %>
    </div>
    <div>
        <%=
            form.number_field :user_id,
            id: :category_user_id,
            value: current_user.id,
            type: :hidden
        %>
    </div>

    <%= form.submit btn_msg, class: "
    flex items-center justify-center
    bg-green-700 hover:bg-green-800 text-white
    py-2 px-6 w-full sm:w-auto
    text-lg
    rounded-md
    cursor-pointer
    transition duration-200
    "%>
<% end %>

app/views/categories/edit.html.erb
<div class="w-full h-full flex flex-col justify-start items-center">
    <div class="
    flex flex-col
    w-3/4 lg:w-1/2
    ">  
        <%# navigation %>
        <div class="flex">
            <a href="javascript:history.back()" class = "
            w-12 py-2 px-4
            text-white font-bold text-center
            bg-gray-600 hover:bg-gray-700
            rounded-lg
            cursor-pointer
            transition-all duration-200
            mb-4 mr-4
            ">
                ←
            </a>
            <a href=<%= categories_path %> class = "
            py-2 px-4
            text-white font-bold text-center
            bg-gray-600 hover:bg-gray-700
            rounded-lg
            cursor-pointer
            transition-all duration-200
            mb-4
            ">
                All categories
            </a>
        </div>

        <%# header %>
        <h1 class="text-4xl mb-6">
            Edit Category
        </h1>

        <%# form proper %>
        <%= render "form", category: @category, btn_msg: "Update" %>
    </div>
</div>

app/views/categories/index.html.erb
<div class="w-full h-full -mx-3">
    <h1 class="text-4xl mb-3 mx-3">Task Categories</h1>

    <div class="flex flex-wrap">
        <% @categories.each do |category| %>
            <%= render 'card', category: category %>
        <% end %>

        <%# add new category %>
        <div class="w-80 xl:w-1/4">
            <a href=<%= new_category_path %> class="
            flex flex-col justify-center items-center
            rounded-lg shadow-md
            px-7 py-6 h-56 m-3
            bg-opacity-50 hover:bg-opacity-100
            bg-gray-700 
            transition duration-200
            ">
                <p class="text-5xl font-thin text-gray-400">+</p>
            </a>
        </div>
    </div>
</div>

app/views/categories/new.html.erb
<div class="w-full h-full flex flex-col justify-start items-center">
    <div class="
    flex flex-col
    w-3/4 lg:w-1/2
    ">  
        <%# navigation %>
        <div class="flex">
            <a href="javascript:history.back()" class = "
            w-12 py-2 px-4
            text-white font-bold text-center
            bg-gray-600 hover:bg-gray-700
            rounded-lg
            cursor-pointer
            transition-all duration-200
            mb-4 mr-4
            ">
                ←
            </a>
            <a href=<%= categories_path %> class = "
            py-2 px-4
            text-white font-bold text-center
            bg-gray-600 hover:bg-gray-700
            rounded-lg
            cursor-pointer
            transition-all duration-200
            mb-4
            ">
                All categories
            </a>
        </div>

        <%# header %>
        <h1 class="text-4xl mb-6">
            New Category
        </h1>

        <%# form proper %>
        <%= render "form", category: @category, btn_msg: "Add" %>
    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Taskly</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application' %> <%# https://stackoverflow.com/questions/59831329/rails-6-and-tailwind-css-does-not-deploy-to-heroku %>
  </head>

  <body class="
  flex flex-col
  bg-gray-800 text-white h-screen
  ">
    <header class="sticky top-0 z-50">
      <%# navbar %>
      <div class="
      flex justify-between items-center
      h-16 px-16
      bg-green-800 
      text-xl text-white
      ">
        <%# left nav-items %>
        <ul class="flex items-center h-full">
          <%# logo %>
          <li class="cursor-pointer select-none mr-6">
            <a href="/" class="text-3xl">
              <i class="fas fa-feather-alt text-2xl mr-2"></i>Taskly
            </a>
          </li>
          <li class="h-full hidden xl:flex items-center justify-center">
            <a href="/" class="
            flex items-center justify-center
            h-full px-4 
            hover:bg-green-700 transition-all duration-200
            ">
              Home
            </a>
          </li>
          <li class="h-full flex items-center justify-center">
            <a href=<%= categories_path %> class="
            hidden md:flex items-center justify-center
            h-full px-4 
            hover:bg-green-700 transition-all duration-200
            ">
              Categories
            </a>
          </li>
          <li class="h-full flex items-center justify-center">
            <a href=<%= custom_tasks_list_path %> class="
            flex items-center justify-center
            h-full px-4 
            hover:bg-green-700 transition-all duration-200
            ">
              Tasks
            </a>
          </li>
        </ul>

        <%# right nav-items %>
        <ul class="flex items-center h-full">
          <% if user_signed_in? %>
            <li class="h-full hidden xl:flex items-center justify-center">
              <div class= "px-4 py-5 h-full">
                Welcome, <%= current_user.email %>!
              </div>
            </li>
            <li class="h-full flex items-center justify-center">
              <a href=<%= edit_user_registration_path%> class="
              hidden md:flex items-center justify-center
              h-full px-4 
              hover:bg-green-700 transition-all duration-200
              ">
                <i class="fas fa-user-edit mr-2"></i> Edit profile
              </a>
            </li>
            <li class="h-full flex items-center justify-center">
              <%=
                link_to raw("<i class=\"fas fa-sign-out-alt mr-2\"></i>Logout"),
                destroy_user_session_path,
                method: :delete,
                class: "
                flex items-center justify-center
                h-full px-4 
                hover:bg-red-800 transition-all duration-200
                "
              %>
            </li>
          <% else %>
            <li class="h-full flex items-center justify-center">
              <%=
                link_to raw("<i class=\"fas fa-user-plus mr-3\"></i> Sign up"),
                new_user_registration_path,
                class: "
                flex items-center justify-center
                h-full px-4 
                hover:bg-green-700 transition-all duration-200
                "
              %>
            </li>
            <li class="h-full flex items-center justify-center">
              <%=
                link_to raw("<i class=\"fas fa-sign-in-alt mr-3\"></i> Login"),
                new_user_session_path,
                class: "
                flex items-center justify-center
                h-full px-4 
                hover:bg-green-700 transition-all duration-200
                "
              %>
            </li>
          <% end %>
        </ul>
      </div>
    </header>
    
    <main class="
    flex flex-col
    flex-grow
    px-16 py-8
    ">
      <%# notice %>
      <% if notice %>
        <%= render "/shared/notice_success", notice: notice %>
      <% end %>
      <% if alert %>
        <%= render "/shared/notice_danger", notice: alert %>
      <% end %>

      <%# render page %>
      <%= yield %>
    </main>
  </body>
</html>

app/views/main/index.html.erb
<div id="main" class="
flex justify-center items-center
-mx-16 -my-8 flex-grow
">
    For the future, if I want a custom home page
</div>

app/views/shared/_notice_danger.html.erb
<p class="
flex justify-center items-center self-center
w-full px-6 py-4
rounded-lg shadow-2xl 
bg-red-200 text-red-800
mb-6
">
    <%= notice %>
</p>

app/views/shared/_notice_success.html.erb
<p class="
flex justify-center items-center self-center
w-full px-6 py-4
rounded-lg shadow-2xl 
bg-green-200 text-green-800
<%# bg-green-600 %>
mb-6
">
    <%= notice %>
</p>

app/views/shared/_tooltip.html.erb
<span class="
tooltip
px-4 py-2
bg-gray-700
text-white text-sm
rounded shadow-xl
<%= classes if defined?(classes) %>
">
    <%= msg %>
</span>

app/views/tasks/_add_task.html.erb
    <a href=<%= new_category_task_path(category) %> class="
    flex items-center justify-center
    h-14 px-4 mb-4
    rounded-lg
    text-gray-400 hover:text-white
    bg-opacity-50 hover:bg-opacity-100
    bg-gray-700
    shadow-md hover:shadow-xl
    transition duration
    ">
        <i class="fas fa-plus mr-3"></i> Add task
    </a>

app/views/tasks/_task.html.erb
<%# TODO: update task.complete when pressed %>

<div class="
flex items-center justify-
h-14 px-4 mb-4
rounded-lg
bg-gray-700
shadow-md hover:shadow-xl
<%= "text-gray-500 line-through" if task.complete %>
transition duration
">
    <%# completion status %>
    <div class="
    flex items-center justify-start
    w-1/2 lg:w-1/4
    cursor-default
    ">
        <%= form_with class: "flex justify-center items-center", model: [ task.category, task ] do |f| %>
            <%= f.check_box :complete, class: "w-5 h-5 mr-3", onchange: "this.form.submit();" %>
        <% end %>

        <a href=<%= category_task_path(@category, task.id) %> class="
        hover:text-gray-300
        ">
            <%= task.name %>
        </a>
    </div>

    <%# due date %>
    <div class="
    hidden lg:flex justify-center items-center
    w-1/2
    cursor-default
    has-tooltip
    <%= task.date.nil? || task.complete ? "text-gray-500" : "text-yellow-200" %>
    ">
        <% if !task.date.nil? %>
            <i class="far fa-calendar text-xl mr-2"></i> <%= task.date.strftime("%B %d, %Y") %>
            <%= render 'shared/tooltip', msg: task.date.strftime("%B %d, %Y"), classes: "-mt-16" %>
        <% else %>
            <i class="far fa-calendar-times text-xl mr-2"></i> No date
        <% end %>
    </div>

    <%# navigation %>
    <div class="flex-grow flex justify-end">
        <a href=<%= category_task_path(@category, task.id) %> class="
        h-full mr-5 text-xl
        text-green-400 hover:text-green-500
        has-tooltip
        ">
            <i class="fas fa-expand-arrows-alt"></i>
            <%= render 'shared/tooltip', msg: "Expand"%>
        </a>
        <a href=<%= edit_category_task_path(@category, task.id) %> class="
        h-full mr-4 text-xl
        text-blue-400 hover:text-blue-500
        has-tooltip
        ">
            <i class="far fa-edit"></i>
            <%= render 'shared/tooltip', msg: "Edit" %>
        </a>
        <%# TODO: add tooltip for delete %>
        <%=
            link_to [task.category, task],
                method: :delete,
                data: { confirm: "Are you sure?" },
                class: "
                h-full text-xl
                text-red-400 hover:text-red-500
                has-tooltip
                " do
        %>
            <i class="far fa-trash-alt"></i>
            <%= render 'shared/tooltip', msg: "Delete" %>
        <% end %>
    </div>
</div>

app/views/tasks/_task_cat.html.erb
<%# TODO: update task.complete when pressed %>
<%# TODO: sort by due date %>

<div class="
flex items-center justify-
h-14 px-4 mb-4
rounded-lg
bg-gray-700
shadow-md hover:shadow-xl
<%= "text-gray-500 line-through" if task.complete %>
transition duration
">
    <%# completion status %>
    <div class="
    flex items-center justify-start
    w-full sm:w-5/12
    cursor-default
    ">
        <%# checkbox %>
        <%= form_with class: "flex justify-center items-center", model: [ task.category, task ] do |f| %>
            <%= f.check_box :complete, class: "w-5 h-5 mr-3", onchange: "this.form.submit();" %>
        <% end %>
        
        <%# task name %>
        <a href=<%= category_task_path(task.category, task.id) %> class="
        hover:text-gray-300 mr-2
        ">
            <%= task.name %>
        </a>

        <%# category title %>
        <a href=<%= category_path(task.category) %> class="
        <% if task.complete %>
            text-gray-500 border-gray-500
            hover:text-gray-300 hover:border-gray-300
        <% else %>
            text-purple-400 border-purple-400
            hover:text-purple-500 hover:border-purple-500
        <% end %>
        border-2 px-1 py-0.5 rounded-lg
        hidden lg:block
        ">
            <%= task.category.title %>
        </a>
    </div>

    <%# due date %>
    <div class="
    hidden lg:flex justify-center items-center
    flex-grow
    cursor-default
    has-tooltip
    <%= task.date.nil? || task.complete ? "text-gray-500" : "text-yellow-200" %>
    ">
        <% if !task.date.nil? %>
            <i class="far fa-calendar text-xl mr-2"></i> <%= task.date.strftime("%B %d, %Y") %>
            <%= render 'shared/tooltip', msg: task.date.strftime("%B %d, %Y"), classes: "-mt-16" %>
        <% else %>
            <i class="far fa-calendar-times text-xl mr-2"></i> No date
        <% end %>
    </div>

    <%# navigation %>
    <div class="
    flex-grow lg:w-5/12 
    hidden sm:flex justify-end
    ">
        <a href=<%= category_task_path(task.category, task.id) %> class="
        h-full mr-5 text-xl
        text-green-400 hover:text-green-500
        has-tooltip
        ">
            <i class="fas fa-expand-arrows-alt"></i>
            <%= render 'shared/tooltip', msg: "Expand"%>
        </a>
        <a href=<%= edit_category_task_path(task.category, task.id) %> class="
        h-full mr-4 text-xl
        text-blue-400 hover:text-blue-500
        has-tooltip
        ">
            <i class="far fa-edit"></i>
            <%= render 'shared/tooltip', msg: "Edit" %>
        </a>
        <%=
            link_to [task.category, task],
                method: :delete,
                data: { confirm: "Are you sure?" },
                class: "
                h-full text-xl
                text-red-400 hover:text-red-500
                has-tooltip
                " do
        %>
            <i class="far fa-trash-alt"></i>
            <%= render 'shared/tooltip', msg: "Delete" %>
        <% end %>
    </div>
</div>

app/views/tasks/edit.html.erb
<div class="w-full h-full flex flex-col justify-start items-center">
    <div class="
    flex flex-col
    w-3/4 lg:w-1/2
    ">  
        <%# navigation %>
        <div class="flex">
            <a href="javascript:history.back()" class = "
            w-12 py-2 px-4
            text-white font-bold text-center
            bg-gray-600 hover:bg-gray-700
            rounded-lg
            cursor-pointer
            transition-all duration-200
            mb-4 mr-4
            ">
                ←
            </a>
            <a href=<%= category_path(@category) %> class = "
            py-2 px-4
            text-white font-bold text-center
            bg-gray-600 hover:bg-gray-700
            rounded-lg
            cursor-pointer
            transition-all duration-200
            mb-4
            ">
                All tasks
            </a>
        </div>
        
        <%# header %>
        <h1 class="text-4xl mb-6">
            Edit Task
        </h1>

        <%# form proper %>
        <%= render "form", category: @category, task: @task, btn_msg: "Update" %>
    </div>
</div>

app/views/tasks/index.html.erb
<div class="w-full h-full">
    <div class="flex items-center mb-6">
        <%# header %>
        <h1 class="text-4xl mr-5">
            <%= @category.title %> Tasks
        </h1>

        <%# navigation %>
        <div class="flex text-3xl">

            <%# back %>
            <a href=<%= categories_path %> class="
            h-full mr-5
            text-green-400 hover:text-green-500
            has-tooltip
            ">
                <i class="fas fa-long-arrow-alt-left"></i>
                <%= render 'shared/tooltip', msg: "Back" %>
            </a>

            <%# edit %>
            <a href=<%= edit_category_path(@category) %> class="
            h-full mr-4
            text-blue-400 hover:text-blue-500
            has-tooltip
            ">
                <i class="far fa-edit"></i>
                <%= render 'shared/tooltip', msg: "Edit" %>
            </a>

            <%# delete %>
            <%# TODO: add tooltip for delete %>
            <%=
                link_to @category,
                    method: :delete,
                    data: { confirm: "Are you sure?" },
                    class: "
                    h-full
                    text-red-400 hover:text-red-500
                    has-tooltip
                    " do
            %>
                <i class="far fa-trash-alt"></i>
                <%= render 'shared/tooltip', msg: "Delete" %>
            <% end %>
        </div>
    </div>

    <div class="mb-6">
        <%# header %>
        <h1 class="text-3xl mb-4">
            Overdue
        </h1>

        <%# tasks %>
        <%= render @tasks_overdue %>

        <%# add task %>
        <%= render "add_task", category: @category%>
    </div>

    <div class="mb-6">
        <%# header %>
        <h1 class="text-3xl mb-4">
            Today
        </h1>

        <%# tasks %>
        <%= render @tasks_today %>

        <%# add task %>
        <%= render "add_task", category: @category%>
    </div>

    <div class="mb-6">
        <%# header %>
        <h1 class="text-3xl mb-4">
            After Today
        </h1>

        <%# tasks %>
        <%= render @tasks_after_today %>

        <%# add task %>
        <%= render "add_task", category: @category%>
    </div>

    <div class="mb-6">
        <%# header %>
        <h1 class="text-3xl mb-4">
            No Date
        </h1>

        <%# tasks %>
        <%= render @tasks_no_date %>

        <%# add task %>
        <%= render "add_task", category: @category%>
    </div>
</div>

app/views/tasks/show.html.erb
<div class="w-full h-full">
    <%# header %>
    <div class="flex items-center mb-3">
        <%# title %>
        <h1 class="text-4xl mr-5">
            <a href=<%= category_path(@category) %> class="
            hover:text-gray-300
            ">
                <%= @category.title %>
            </a> > 
            <span><%= @task.name %></span>
        </h1>

        <%# navigation %>
        <div class="flex text-3xl">
            <%# back %>
            <a href=<%= category_path(@category) %> class="
            h-full mr-5
            text-green-400 hover:text-green-500
            has-tooltip
            ">
                <i class="fas fa-long-arrow-alt-left"></i>
                <%= render 'shared/tooltip', msg: "Back" %>
            </a>

            <%# edit %>
            <a href=<%= edit_category_task_path(@category, @task.id) %> class="
            h-full mr-4
            text-blue-400 hover:text-blue-500
            has-tooltip
            ">
                <i class="far fa-edit"></i>
                <%= render 'shared/tooltip', msg: "Edit" %>
            </a>

            <%# delete %>
            <%=
                link_to [@task.category, @task],
                    method: :delete,
                    data: { confirm: "Are you sure?" },
                    class: "
                    h-full
                    text-red-400 hover:text-red-500
                    has-tooltip
                    " do
            %>
                <i class="far fa-trash-alt"></i>
                <%= render 'shared/tooltip', msg: "Delete" %>
            <% end %>
        </div>
    </div>

    <%# due date %>
    <div class="
    text-2xl cursor-default mb-6
    <%= @task.date.nil? ? "text-gray-500" : "text-yellow-200" %>
    ">
        <% if !@task.date.nil? %>
            <i class="far fa-calendar mr-2"></i> <%= @task.date.strftime("%B %d, %Y") %>
        <% else %>
            <i class="far fa-calendar-times mr-2"></i> No date
        <% end %>
    </div>

    <%# other details %>
    <div class="flex flex-wrap gap-x-5 gap-y-5 mb-5">
        <div class="
        flex justify-center items-center
        rounded-lg shadow-md hover:shadow-xl
        px-7 h-14
        flex-none md:flex-1
        w-full md:w-auto
        bg-gray-700
        transition duration-200
        ">
            <p class="text-lg">
                <i class="fas fa-cut mr-2"></i>Last updated <%= @task.updated_at.strftime("%B %d, %Y") %>
            </p>
        </div>
        <div class="
        flex justify-center items-center
        rounded-lg shadow-md hover:shadow-xl
        px-7 h-14
        flex-none md:flex-1
        w-full md:w-auto
        bg-gray-700
        transition duration-200
        ">
            <p class="text-lg">
                <i class="fas fa-pen mr-2"></i>Created <%= @task.created_at.strftime("%B %d, %Y") %>
            </p>
        </div>
    </div>

    <%# notes %>
    <div class="
    flex flex-col
    rounded-lg shadow-md hover:shadow-xl
    px-7 py-6 h-56
    bg-gray-700
    transition duration-200 mb-5
    ">
        <h2 class="text-3xl mb-3 mr-5">Notes</h2>
        <p class="text-lg">
            <% if @task.notes.length > 0 %>
                <%= @task.notes %>
            <% else %>
                <span class="text-gray-400">No notes</span>
            <% end %>
        </p>
    </div>

    <%# TODO: make completion status togglable by clicking %>
    <%# STATUS %>
    <div class="
    flex flex-col justify-center items-center
    rounded-lg shadow-md hover:shadow-xl
    px-7 py-6 h-14
    <%= @task.complete ? "bg-green-500" : "bg-yellow-500" %>
    text-lg
    transition duration-200
    cursor-default
    ">
        <% if @task.complete %>
            <span>
                <i class="fas fa-check-circle mr-1"></i>
                Completed
            </span>
        <% else %>
            <span>
                <i class="fas fa-hourglass-half mr-1"></i>
                Incomplete
            </span>
        <% end %>
    </div>
</div>